### ISSUE TITLE
use database后删除当前进入的database，然后报错

### ISSUE THREAD

**Issue by ghost** [polardb/polardbx-sql#124]
(venv) [root@polardbx02 ~]# mysql -h192.168.58.111 -P56863 -upolardbx_root -pyhzjDJkd
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 15
Server version: 5.6.29 Tddl Server (ALIBABA)

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]> create database test1; create database test2;
Query OK, 1 row affected (0.14 sec)

Query OK, 1 row affected (0.15 sec)

MySQL [(none)]> use test1;
Database changed
MySQL [test1]> drop database test1;
Query OK, 0 rows affected (0.27 sec)

MySQL [test1]> show create database test2;
ERROR 1049 (HY000): [15ca74863bc02000][192.168.58.111:56863][test1]Unknown database 'test1'
MySQL [test1]>

**Comment by agapple** [comment]
退出mysql客户端，重新登录下 或者 use切换到test2
