### ISSUE TITLE
Trouble installing PolarDB-X with PXD Tool

### ISSUE THREAD

**Issue by hsien999** [polardb/polardbx-sql#157]
PTAL
I tried to follow the steps in the official documentation (https://www.polardbx.com/document?type=PolarDB-X) for a quick local experience with PolarDB-X. But I always seem to run into problems with the Docker installation process.
I have ensured the following:
1. the internet is open
2. docker is working properly with the required version (20.10.17)
3. docker registry is properly configured with mirrors
As you can see below, it seems that the download/installation process is always retrying.
![image](https://github.com/polardb/polardbx-sql/assets/39696805/16bc489e-35f6-4aa4-8bf4-9e1dfc3a474a)

How do I troubleshoot the problem? Or is there an alternative installation method?

**Comment by vettalwu** [comment]
@hsien999 Execute `docker info` to show your registry mirror configuration.

**Comment by vettalwu** [comment]
Close issue after no response for a long time.
