### ISSUE TITLE
cmake Compilation failed

### ISSUE THREAD

**Issue by cxgyyx** [polardb/polardbx-sql#206]
#Installation dependencies
apt install make automake cmake git bison libaio-dev libncurses-dev libsasl2-dev libldap2-dev libssl-dev pkg-config
Reading package lists... Done
Building dependency tree
Reading state information... Done
automake is already the newest version (1:1.16.1-4ubuntu6).
bison is already the newest version (2:3.5.1+dfsg-1).
libaio-dev is already the newest version (0.3.112-5).
make is already the newest version (4.2.1-1.2).
pkg-config is already the newest version (0.29.1-0ubuntu4).
cmake is already the newest version (3.16.3-1ubuntu1.20.04.1).
git is already the newest version (1:2.25.1-1ubuntu3.11).
libldap2-dev is already the newest version (2.4.49+dfsg-2ubuntu1.10).
libncurses-dev is already the newest version (6.2-0ubuntu2.1).
libsasl2-dev is already the newest version (2.1.27+dfsg-2ubuntu0.1).
libssl-dev is already the newest version (1.1.1f-1ubuntu2.22).
0 upgraded, 0 newly installed, 0 to remove and 203 not upgraded.

#
 cmake .                               	\
    -DFORCE_INSOURCE_BUILD=ON           \
    -DCMAKE_BUILD_TYPE="Debug"          \
    -DSYSCONFDIR="/data/mysql"           \
    -DCMAKE_INSTALL_PREFIX="/data/mysql" \
    -DMYSQL_DATADIR="/data/mysql/data"   \
    -DWITH_BOOST="./extra/boost/boost_1_70_0.tar.gz" 

......
-- CMAKE_BUILD_TYPE: Debug
-- COMPILE_DEFINITIONS: _GNU_SOURCE;_FILE_OFFSET_BITS=64;RAPIDJSON_NO_SIZETYPEDEFINE;RAPIDJSON_SCHEMA_USE_INTERNALREGEX=0;RAPIDJSON_SCHEMA_USE_STDREGEX=1;WITH_XENGINE_STORAGE_ENGINE;WITH_QUERY_TRACE;HAVE_CONFIG_H;HAVE_OPENSSL;__STDC_LIMIT_MACROS;__STDC_FORMAT_MACROS;_USE_MATH_DEFINES;LZ4_DISABLE_DEPRECATE_WARNINGS;HAVE_TLSv13;HAVE_LIBEVENT2;UNISTR_FROM_STRING_EXPLICIT=explicit;UNISTR_FROM_CHAR_EXPLICIT=explicit
-- CMAKE_C_FLAGS: -fno-omit-frame-pointer  -Wall -Wextra -Wformat-security -Wvla -Wundef -Wmissing-format-attribute -Wwrite-strings -Wjump-misses-init
-- CMAKE_CXX_FLAGS: -DNORMANDY_CLUSTER -std=c++14 -fno-omit-frame-pointer  -Wall -Wextra -Wformat-security -Wvla -Wundef -Wmissing-format-attribute -Woverloaded-virtual -Wcast-qual -Wimplicit-fallthrough=2 -Wlogical-op
-- CMAKE_CXX_FLAGS_DEBUG: -DSAFE_MUTEX -DENABLED_DEBUG_SYNC -g
-- CMAKE_CXX_FLAGS_RELWITHDEBINFO: -DDBUG_OFF -ffunction-sections -fdata-sections -O2 -g -DNDEBUG
-- CMAKE_CXX_FLAGS_RELEASE: -DDBUG_OFF -ffunction-sections -fdata-sections -O3 -DNDEBUG
-- CMAKE_CXX_FLAGS_MINSIZEREL: -DDBUG_OFF -ffunction-sections -fdata-sections -Os -DNDEBUG
-- CMAKE_C_LINK_FLAGS:  -fuse-ld=gold -Wl,--gc-sections
-- CMAKE_CXX_LINK_FLAGS:  -fuse-ld=gold -Wl,--gc-sections
-- CMAKE_EXE_LINKER_FLAGS
-- CMAKE_MODULE_LINKER_FLAGS
-- CMAKE_SHARED_LINKER_FLAGS
-- Configuring done
CMake Error at mysys/CMakeLists.txt:179 (ADD_DEPENDENCIES):
  The dependency target "libcrypto" of target "mysys" does not exist.

CMake Error at mysys/CMakeLists.txt:179 (ADD_DEPENDENCIES):
  The dependency target "libssl" of target "mysys" does not exist.

CMake Error at router/src/http/src/CMakeLists.txt:44 (ADD_DEPENDENCIES):
  The dependency target "libcrypto" of target "http_common" does not exist.

CMake Error at router/src/http/src/CMakeLists.txt:44 (ADD_DEPENDENCIES):
  The dependency target "libssl" of target "http_common" does not exist.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by ZSYTY** [comment]
Try adding this option for cmake: `-DWITH_SSL=openssl`

**Comment by cxgyyx** [comment]
> Try adding this option for cmake: `-DWITH_SSL=openssl`

Thank you very much
