### ISSUE TITLE
用kind创建集群是，所有节点一直处于creating状态

### ISSUE THREAD

**Issue by lichx123** [polardb/polardbx-sql#60]
[root@my_ob ~]# kubectl get polardbxcluster -w
NAME          GMS   CN    DN    CDC   PHASE      DISK   AGE
quick-start   0/1   0/1   0/1   0/1   Creating          8m6s

**Comment by Cleverdada** [comment]
集群创建卡在 Creating 状态有几种可能的原因
● 组件的 Pod 始终无法 ready，可能的状态可能有 ImagePullBackOff，Pending，CrashBackLoopOff 等
● GMS 中 metadb 的元数据无法准备完成
● 无法从 CN 处获取版本
● ...

排查思路主要是两个：
1. 查看本集群 Pod 状态，看是否有异常状态的 Pod
`kubectl get pods -l polardbx/name={集群名}`

![image](https://user-images.githubusercontent.com/11186845/171346144-c6d99c65-99b3-4cd3-b0e3-5540b9bff50f.png)


2. 查看 polardbx-operator 日志，查看是否有对应集群的 ERROR 日志, 根据报错再具体分析, 命令如下：
`kubectl -n $namespace logs $container_name`

**Comment by vettalwu** [comment]
Close issue after no response for a long time.
