### ISSUE TITLE
The file content is empty

### ISSUE THREAD

**Issue by co63oc** [polardb/polardbx-sql#99]
https://github.com/ApsaraDB/galaxysql/blob/main/polardbx-server/src/main/java/com/alibaba/polardbx/config/loader/ManagerAppLoader.java

The file content is empty

**Comment by co63oc** [comment]
Following files are the same problem:
./polardbx-gms/src/main/java/com/alibaba/polardbx/gms/tablegroup/TableGroupOutlineRecord.java
./polardbx-gms/src/test/java/com/alibaba/polardbx/gms/partition/PartitionAccessorTest.java
./polardbx-transaction/src/main/java/com/alibaba/polardbx/transaction/BestEffortTransaction.java
./polardbx-transaction/src/main/java/com/alibaba/polardbx/transaction/TransactionMetrics.java
./polardbx-transaction/src/main/java/com/alibaba/polardbx/transaction/async/ScanBestEffortPreparedTask.java
./polardbx-parser/src/main/java/com/alibaba/polardbx/druid/sql/dialect/oracle/parser/OracleStatementParser.java
./polardbx-parser/src/test/java/com/alibaba/polardbx/druid/bvt/sql/oracle/pl/Oracle_pl_for_5.java
./polardbx-parser/src/test/java/com/alibaba/polardbx/druid/bvt/sql/oracle/block/OracleBlockTest28.java
./polardbx-parser/src/test/java/com/alibaba/polardbx/druid/bvt/sql/mysql/ads_ddl_bug.java
./polardbx-parser/src/test/java/com/alibaba/polardbx/druid/bvt/sql/mysql/createTable/ADB30_MySqlDDLTest.java
./polardbx-parser/src/test/java/com/alibaba/polardbx/druid/bvt/sql/odps/OdpsSelectTest44_udtf_alias.java
./polardbx-parser/src/test/java/com/alibaba/polardbx/druid/bvt/sql/odps/OdpsFormatCommentTest25.java
./polardbx-parser/src/test/java/com/alibaba/polardbx/druid/bvt/sql/oceanbase/OceanbaseAlterTableAddPartitionTest2.java
./polardbx-parser/src/test/java/com/alibaba/polardbx/druid/bvt/sql/ads/ADS_CreateTable_2_mysql.java
./polardbx-parser/src/test/java/com/alibaba/polardbx/druid/bvt/sql/hive/HiveDropFunc_1.java
./polardbx-parser/src/test/java/com/alibaba/polardbx/druid/bvt/sql/hive/HiveDropFunc_0.java
./polardbx-server/src/main/java/com/alibaba/polardbx/matrix/jdbc/TDatabaseMetaData.java
./polardbx-server/src/main/java/com/alibaba/polardbx/matrix/jdbc/TCallableStatement.java
./polardbx-server/src/main/java/com/alibaba/polardbx/matrix/monitor/MatrixRegisterHelper.java
./polardbx-server/src/main/java/com/alibaba/polardbx/server/statistics/StatsRpcClient.java
./polardbx-server/src/main/java/com/alibaba/polardbx/server/response/ShowProcedureCache.java
./polardbx-server/src/main/java/com/alibaba/polardbx/server/handler/privileges/GrantHandler.java
./polardbx-server/src/main/java/com/alibaba/polardbx/server/handler/privileges/RevokeHandler.java
./polardbx-server/src/main/java/com/alibaba/polardbx/config/loader/ManagerAppLoader.java
./polardbx-optimizer/src/main/java/com/alibaba/polardbx/optimizer/utils/CheckGsiColumnLenUtils.java
./polardbx-optimizer/src/main/java/com/alibaba/polardbx/optimizer/view/DrdsSystemTableView.java
./polardbx-optimizer/src/main/java/com/alibaba/polardbx/optimizer/core/sequence/bean/SequenceFactory.java
./polardbx-optimizer/src/main/java/com/alibaba/polardbx/optimizer/core/rel/segmented/rule/BetweenTableScanSplitRule.java
./polardbx-optimizer/src/main/java/com/alibaba/polardbx/optimizer/core/rel/segmented/SegmentedSharding.java
./polardbx-optimizer/src/main/java/com/alibaba/polardbx/optimizer/core/rel/PhyDDLViewBuilder.java
./polardbx-optimizer/src/main/java/com/alibaba/polardbx/optimizer/core/rel/DataDefLanguageLogicView.java
./polardbx-optimizer/src/main/java/com/alibaba/polardbx/optimizer/core/rel/PartitionTableDdlView.java
./polardbx-optimizer/src/main/java/com/alibaba/polardbx/optimizer/config/table/charset/CharsetFactoryImpl.java
./polardbx-optimizer/src/main/java/com/alibaba/polardbx/optimizer/config/table/parse/TableMetaParser.java
./polardbx-optimizer/src/main/java/com/alibaba/polardbx/optimizer/config/table/statistic/AutoAnalyzeTask.java
./polardbx-optimizer/src/main/java/com/alibaba/polardbx/optimizer/config/table/ScaleOutMetaManager.java
./polardbx-optimizer/src/test/java/com/alibaba/polardbx/optimizer/core/function/ExtraFunctionManagerTest.java
./polardbx-optimizer/src/test/java/com/alibaba/polardbx/optimizer/config/table/charset/CharsetFactoryTest.java
./polardbx-calcite/src/main/java/org/apache/calcite/rel/logical/LogicalSqlNodeView.java
./polardbx-calcite/src/main/java/org/apache/calcite/rel/logical/LogicalCreateTable.java
./polardbx-calcite/src/main/java/org/apache/calcite/rel/logical/LogicalCreateIndex.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/atom/securety/impl/PasswordCoderCDBImpl.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/vectorized/compare/AndLongColLongColLongColLongColVectorizedExpression.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/vectorized/compare/AndLongColLongColLongColLongColLongColVectorizedExpression.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/vectorized/compare/OrLongColLongColLongColLongColLongColVectorizedExpression.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/vectorized/compare/OrLongColLongColLongColLongColVectorizedExpression.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/vectorized/compare/OrLongColLongColLongColVectorizedExpression.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/vectorized/compare/AndLongColLongColLongColVectorizedExpression.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/scheduler/executor/RebalanceScheduledJob.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/sync/BaselineValidateSyncAction.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/sync/FetchStatisticTaskInfoSyncAction.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/sync/UpdateBaselineSyncAction.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/sync/UpdatePlanInfoSyncAction.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/sync/BaselineClearSyncAction.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/utils/DdlUtils.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/gms/util/AlterPartitionKeyUtils.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/gms/util/DdlGmsUtils.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/statistic/MysqlStatisticCollector.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/statistic/entity/DrdsSystemTableColumnStatistic.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/statistic/StatisticBuilder.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/accumulator/AccumulatorBuilders.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/ddl/job/factory/TruncateTableWithGsiJobFactory.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/ddl/job/builder/gsi/TruncateTableWithGsiBuilder.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/ddl/engine/AsyncDDLManager.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/ddl/newengine/job/wrapper/ExecutableDdlJob4CreateTableWithGsi.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/ddl/newengine/job/wrapper/ExecutableDdlJob4TruncateTableWithGsiCutOver.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/ddl/newengine/job/wrapper/ExecutableDdlJob4DropTableWithGsi.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/balancer/splitpartition/IndexBasedSplitter.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/balancer/splitpartition/SampleBasedSplitPointBuilder.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/handler/subhandler/InformationSchemaColumnStatisticsHandler.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/handler/subhandler/InformationSchemaColumnsHandler.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/handler/subhandler/InformationSchemaStatisticsHandler.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/handler/subhandler/InformationSchemaStatisticTaskHandler.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/handler/subhandler/InformationSchemaTableConstraintsHandler.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/executor/handler/LogicalShowColumnsHandler.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/sequence/impl/DefaultSequence.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/sequence/util/RandomSequence.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/sequence/util/SequenceHelper.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/repo/mysql/handler/SequenceSingleHandler.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/repo/mysql/handler/ddl/AsyncDDLRemoveJobHandler.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/repo/mysql/handler/DDLNewHandler.java
./polardbx-executor/src/main/java/com/alibaba/polardbx/repo/mysql/handler/ProcedureCallHandler.java
./polardbx-executor/src/test/java/com/alibaba/polardbx/executor/operator/expression/vectorized/binding/BindingTest.java
./polardbx-executor/src/test/java/com/alibaba/polardbx/sequence/util/RandomBalanceTest.java
./polardbx-executor/src/test/java/com/alibaba/polardbx/sequence/util/RandomSequenceTest.java
./polardbx-rule/src/main/java/com/alibaba/polardbx/rule/enumerator/HotspotEnumeratorImpl.java
./polardbx-rule/src/main/java/com/alibaba/polardbx/rule/model/ShardPrepareResult.java

**Comment by hustfxj** [comment]
@co63oc Thank you very much. We will check it.
